/**
 * What the generated Dockerfile needs from the target: its id (the image's `/opt/targets/<id>`),
 * the package pnpm installs for, the workspace packages the capture holds (directory under
 * `packages/` and package name, for the relinks), the reviewed promotion set, and whether the
 * pin has a `.npmrc`.
 */
export interface DockerfileSpec {
  readonly id: string
  readonly filter: string
  readonly captured: readonly { readonly dir: string; readonly name: string }[]
  readonly expectedPromoted: readonly string[]
  readonly npmrc: boolean
}

/** Printed by the promotion step with the set it promoted, whether or not it then fails. */
export const PROMOTED_MARKER = "b4-factory promoted:"
/** Printed on stderr, with the reviewed set, when the promoted set differs from it. */
export const EXPECTED_MARKER = "b4-factory expected promoted:"

/**
 * Each marker as the step PRINTS it, on one of BuildKit's `#<step> <seconds> ` output lines and
 * followed by names to the end of the line. BuildKit echoes the RUN line into the log, where
 * both markers are followed by `$actual"` and `$expected"`, so a match may hold no `$` and no
 * quote; its error summary repeats the output without the step number, so that never matches.
 */
const PROMOTED_LINE = /^#(\d+) \S+ b4-factory promoted:([^\n$"]*)$/gm
const EXPECTED_LINE = /^#(\d+) \S+ b4-factory expected promoted:[^\n$"]*$/gm

/**
 * What may appear unquoted in the step's shell, and where: an id or a directory is one path
 * segment (`/opt/targets/<id>`, `packages/<dir>`), a package name is `<name>` or
 * `@<scope>/<name>` (`node_modules/<name>`). No segment may start with a dot, so `.` and `..`
 * never reach an `rm -rf`, and a directory can never disagree with `CAPTURED`'s `packages/<p>`.
 * A name's segments start with a letter or digit, so the filter can never read as a flag.
 */
const SEGMENT = /^[A-Za-z0-9_-][A-Za-z0-9._-]*$/
const NAME = /^(?:@[A-Za-z0-9][A-Za-z0-9._-]*\/)?[A-Za-z0-9][A-Za-z0-9._-]*$/

function refuseUnsafe(value: string, pattern: RegExp): void {
  if (!pattern.test(value))
    throw new Error(`target:init will not write ${JSON.stringify(value)} into a Dockerfile's shell`)
}

function refuseRepeated(names: readonly string[]): void {
  const seen = new Set<string>()
  for (const name of names) {
    if (seen.has(name)) throw new Error(`The promotion set names ${name} twice`)
    seen.add(name)
  }
}

/** By code unit, as the step's `LC_ALL=C sort` orders. */
const byCodeUnit = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

export function renderDockerfile(spec: DockerfileSpec): string {
  refuseUnsafe(spec.id, SEGMENT)
  for (const dir of spec.captured.map((p) => p.dir)) refuseUnsafe(dir, SEGMENT)
  for (const name of [spec.filter, ...spec.captured.map((p) => p.name), ...spec.expectedPromoted])
    refuseUnsafe(name, NAME)
  refuseRepeated(spec.expectedPromoted)
  const packages = [...spec.captured].sort((a, b) => byCodeUnit(a.dir, b.dir))
  const opt = `/opt/targets/${spec.id}`
  const roots = ["package.json", "pnpm-workspace.yaml", "pnpm-lock.yaml"]
  if (spec.npmrc) roots.push(".npmrc")
  const captured = packages.map((p) => p.dir).join(" ")
  const links = packages.map((p) => `${p.name}=${p.dir}`).join(" ")
  const expected = [...spec.expectedPromoted].sort(byCodeUnit).join(" ")
  return `# Generated by target:init for ${spec.filter}: a target file, reviewed and committed by a person.
ARG BASE_IMAGE=node:24-slim
ARG PLATFORM=linux/arm64
FROM --platform=\${PLATFORM} \${BASE_IMAGE}
ARG PNPM_VERSION
# git for the workspace baseline; pnpm via npm, not corepack, because corepack caches the
# binary in the enabling user's home and the container runs as node with no network.
# git is resolved by apt at build time and is not part of the recorded image inputs; an
# accepted gap, recorded in the rung 2 spec's risks.
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/* \\
 && npm install -g pnpm@\${PNPM_VERSION}
WORKDIR ${opt}
COPY ${roots.join(" ")} ./
# The context is the target's imageContext: the manifest of every package the install below
# reaches, and config packages whole.
COPY packages packages
# Hoisted, so one root node_modules holds everything and the workspace needs one link. The
# chmod stays in this layer: in a layer of its own it copies the install up and doubles the image.
RUN pnpm install --frozen-lockfile --filter ${spec.filter}... --ignore-scripts --config.node-linker=hoisted \\
 && chmod -R a+rX ${opt}
# The workspace holds exactly ONE environment link (node_modules, at its root): the inspection
# that snapshots it refuses a symlink anywhere else. So everything a captured package resolves
# must be in the ROOT node_modules:
#  1. When a captured package nests its own typescript, the root's (the tsc every package
#     builds with) moves aside first and tsc becomes a shim onto it.
#  2. A dependency hoisting left under packages/<p>/node_modules (its version conflicts with
#     the root's) is promoted over the root's. EXPECTED_PROMOTED is that set, reviewed: any
#     other set, or one name promoted twice, fails the build rather than silently replacing a
#     root package the other packages resolve. target:measure proposes it from a failed build.
#  3. Workspace links are pointed from the image's manifest-only copies at the workspace's own
#     packages. CAPTURED is the packages the capture holds; target:prepare checks it. A
#     promoted name that is also a workspace package fails the build: its link would replace it.
# Every chain inside a loop ends in \`|| exit 1\`: this RUN is one && list, where the shell ignores
# set -e, and a loop's status is only its last iteration's.
RUN set -eu \\
 && CAPTURED="${captured}" \\
 && EXPECTED_PROMOTED="${expected}" \\
 && NESTED_TS="" \\
 && for p in $CAPTURED; do if [ -d "packages/$p/node_modules/typescript" ] && [ ! -L "packages/$p/node_modules/typescript" ]; then NESTED_TS=1; fi; done \\
 && if [ -n "$NESTED_TS" ] && [ -d node_modules/typescript ]; then \\
      mkdir -p tools/node_modules && mv node_modules/typescript tools/node_modules/typescript \\
      && rm -f node_modules/.bin/tsc \\
      && printf '#!/bin/sh\\nexec node ${opt}/tools/node_modules/typescript/bin/tsc "$@"\\n' > node_modules/.bin/tsc \\
      && chmod 755 node_modules/.bin/tsc; \\
    fi \\
 && PROMOTED="" \\
 && for p in $CAPTURED; do \\
      nm="packages/$p/node_modules"; [ -d "$nm" ] || continue; \\
      for entry in "$nm"/* "$nm"/@*/*; do \\
        [ -e "$entry" ] || continue; \\
        if [ -L "$entry" ]; then continue; fi; \\
        rel="\${entry#"$nm"/}"; \\
        case "$rel" in @*/*) ;; @*) continue ;; esac; \\
        case " $PROMOTED " in *" $rel "*) echo "promoted twice: $rel (again from packages/$p)" >&2; exit 1 ;; esac; \\
        PROMOTED="$PROMOTED $rel"; \\
        { rm -rf "node_modules/$rel" && mkdir -p "node_modules/$(dirname "$rel")" && mv "$entry" "node_modules/$rel"; } || exit 1; \\
      done; \\
      rm -rf "$nm" || exit 1; \\
    done \\
 && actual="$(printf '%s\\n' $PROMOTED | LC_ALL=C sort | tr '\\n' ' ')" \\
 && expected="$(printf '%s\\n' $EXPECTED_PROMOTED | LC_ALL=C sort | tr '\\n' ' ')" \\
 && echo "${PROMOTED_MARKER} $actual" \\
 && for link in ${links}; do \\
      name="\${link%%=*}"; dir="\${link#*=}"; \\
      case " $PROMOTED " in *" $name "*) echo "promoted $name is a workspace package the image relinks to /workspace/packages/$dir" >&2; exit 1 ;; esac; \\
    done \\
 && if [ "$actual" != "$expected" ]; then echo "${EXPECTED_MARKER} $expected" >&2; exit 1; fi \\
 && for link in ${links}; do \\
      name="\${link%%=*}"; dir="\${link#*=}"; \\
      { rm -rf "node_modules/$name" && mkdir -p "node_modules/$(dirname "$name")" \\
      && ln -s "/workspace/packages/$dir" "node_modules/$name"; } || exit 1; \\
    done
# vite bundles a TypeScript config to a temp file under the NEAREST node_modules, which here is
# the image's read-only one, and it only tolerates EACCES there. Point that one scratch
# directory at /tmp, which the sandbox mounts as a writable tmpfs.
RUN ln -s /tmp ${opt}/node_modules/.vite-temp
USER node
WORKDIR /workspace
`
}

/** The reviewed promotion set a Dockerfile declares, sorted; undefined when it declares none. */
export function expectedPromotedOf(dockerfile: string): string[] | undefined {
  const match = /\bEXPECTED_PROMOTED="([^"]*)"/.exec(dockerfile)
  if (!match) return undefined
  return (match[1] as string)
    .split(/\s+/)
    .filter((name) => name.length > 0)
    .sort()
}

/** `dockerfile` declaring `names` as its promotion set. */
export function withExpectedPromoted(dockerfile: string, names: readonly string[]): string {
  if (expectedPromotedOf(dockerfile) === undefined)
    throw new Error("The Dockerfile declares no EXPECTED_PROMOTED to replace")
  for (const name of names) refuseUnsafe(name, NAME)
  refuseRepeated(names)
  return dockerfile.replace(
    /\bEXPECTED_PROMOTED="[^"]*"/,
    `EXPECTED_PROMOTED="${[...names].sort(byCodeUnit).join(" ")}"`,
  )
}

/**
 * The set a build promoted, when the build failed at the promotion check; undefined when it
 * did not reach the check or passed it. Read from the last promoted marker the failing step
 * (the one that printed the expected marker) printed.
 */
export function promotionMismatch(log: string): string[] | undefined {
  const failed = [...log.matchAll(EXPECTED_LINE)].at(-1)
  if (failed === undefined) return undefined
  const printed = [...log.matchAll(PROMOTED_LINE)].filter((m) => m[1] === failed[1]).at(-1)
  if (printed === undefined) return undefined
  return (printed[2] as string)
    .split(/\s+/)
    .filter((name) => name.length > 0)
    .sort()
}
