// Generated by b4 typegen from src/auth.ts. Do not edit.
import type { AuthDefinition } from "@b4run/sdk"

declare module "@b4run/sdk" {
  interface B4Register {
    principal: typeof import("../src/auth.js").default extends AuthDefinition<infer P> ? P : never
  }
}
