import { mkdtempSync, readFileSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { describe, expect, it } from "vitest"
import {
  configuredImages,
  repositoryRoot,
  TargetSchema,
  targetsDir,
} from "../src/lib/targets/catalog.ts"
import { initTarget } from "../src/lib/targets/init/init.ts"
import { measureTarget } from "../src/lib/targets/measure/measure.ts"
import { writeProposal } from "../src/lib/targets/proposal.ts"
import { parseVitestCommand } from "../src/lib/targets/vitest-command.ts"
import { shippedPin } from "./temp-repo.ts"

describe("target:measure on a devkit target generated by target:init", () => {
  it("proposes exactly the committed nine excludes, each failing alone on the templates the capture omits", async () => {
    const registry = configuredImages()
    if (registry === undefined) throw new Error("the lane setup configured no image registry")
    const targets = mkdtempSync(join(tmpdir(), "factory-measure-lane-"))
    const staging = mkdtempSync(join(tmpdir(), "factory-measure-staging-"))
    const started = Date.now()
    try {
      // initTarget makes the pin present itself (plan I8).
      writeProposal(
        initTarget({
          packageRef: "@b4run/devkit",
          pin: shippedPin("devkit"),
          repositoryRoot: repositoryRoot(),
          targetsDir: targets,
        }).files,
      )
      const measure = () =>
        measureTarget({
          id: "devkit",
          targetsDir: targets,
          repositoryRoot: repositoryRoot(),
          registry,
          stagingRoot: staging,
          signal: AbortSignal.timeout(2_400_000),
          fileTimeoutMs: 120_000,
          memoryMb: 2048,
          cpus: 2,
          runs: 1,
          allowDecrease: false,
          log: (line) => process.stderr.write(`lane: ${line}\n`),
        })
      let outcome = await measure()
      if (outcome.kind === "promotion") {
        // A person reviews and applies this; the lane records it and applies it.
        process.stderr.write(`lane: devkit promotes [${outcome.promoted.join(" ")}]\n`)
        writeProposal(outcome.files)
        outcome = await measure()
      }
      if (outcome.kind !== "measured")
        throw new Error("a second build proposed another promotion set")
      const committed = TargetSchema.parse(
        JSON.parse(readFileSync(join(targetsDir, "devkit", "target.json"), "utf8")),
      )
      const m = outcome.measurement
      expect(m.excludes).toEqual(parseVitestCommand(committed.commands.test).excludes)
      expect(m.test).toEqual(committed.commands.test)
      expect(m.files.filter((f) => f.verdict === "pass").map((f) => f.file)).toEqual([
        "test/process-artifacts.test.ts",
        "test/reporting.test.ts",
      ])
      const excluded = m.files.filter((f) => f.verdict !== "pass")
      expect(excluded).toHaveLength(9)
      for (const file of excluded) {
        expect(file.verdict, file.file).toBe("fail")
        // The failure output names the templates the capture leaves out...
        expect(file.output, file.file).toMatch(/templates\//)
        // ...and measure names each as a capture omission of devkit's templates/ (review I5).
        expect(file.omissions.length, file.file).toBeGreaterThan(0)
        for (const path of file.omissions)
          expect(path, file.file).toMatch(/^packages\/devkit\/templates\//)
        expect(file.reason, file.file).toMatch(/capture omission: "packages\/devkit\/templates\//)
      }
      const record = outcome.files[1]?.after ?? ""
      expect(record.match(/^- `test\//gm)).toHaveLength(9)
      expect(record.match(/capture omission: "packages\/devkit\/templates\//g)).toHaveLength(9)
      expect(m.resources.cpus).toBe(2)
      expect(m.resources.memoryMb).toBeGreaterThanOrEqual(512)
      expect(m.resources.memoryMb).toBeLessThanOrEqual(2048)
      process.stderr.write(
        `lane: measured ${JSON.stringify(m.measured)}; proposed ${JSON.stringify(m.resources)}; committed ${JSON.stringify(committed.resources)}; test ${JSON.stringify(m.test)}; ${Math.round((Date.now() - started) / 1000)} s\n${outcome.report}\n`,
      )
    } finally {
      rmSync(targets, { recursive: true, force: true })
      rmSync(staging, { recursive: true, force: true })
    }
  }, 2_500_000)
})
