import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { describe, expect, it } from "vitest"
import {
  configuredImages,
  loadTargetRecipe,
  repositoryRoot,
  targetsDir,
} from "../src/lib/targets/catalog.ts"
import { type EnsuredImage, ImagePrepareError } from "../src/lib/targets/images.ts"
import {
  expectedPromotedOf,
  promotionMismatch,
  withExpectedPromoted,
} from "../src/lib/targets/init/dockerfile.ts"
import { initTarget } from "../src/lib/targets/init/init.ts"
import { writeProposal } from "../src/lib/targets/proposal.ts"
import { shippedPin } from "./temp-repo.ts"

/**
 * Generate `packageRef`'s target at `id`'s shipped pin into a scratch catalog and build it
 * through the run's registry, learning the promotion set once if the first build names one
 * (what a person does with target:measure's proposal). initTarget makes the pin present
 * itself, so this holds on a shallow checkout whatever the global setup built first.
 */
async function buildGenerated(packageRef: string, id: string) {
  const registry = configuredImages()
  if (registry === undefined) throw new Error("the lane setup configured no image registry")
  const targets = mkdtempSync(join(tmpdir(), `factory-init-lane-${id}-`))
  try {
    writeProposal(
      initTarget({
        packageRef,
        pin: shippedPin(id),
        repositoryRoot: repositoryRoot(),
        targetsDir: targets,
      }).files,
    )
    const ensure = () =>
      registry.ensure(loadTargetRecipe(id, { targetsDir: targets }), {
        signal: AbortSignal.timeout(2_400_000),
      })
    let learned: string[] | undefined
    let ensured: EnsuredImage
    const started = Date.now()
    try {
      ensured = await ensure()
    } catch (error) {
      learned = error instanceof ImagePrepareError ? promotionMismatch(error.log) : undefined
      if (learned === undefined) throw error
      process.stderr.write(
        `lane: the generated ${id} Dockerfile promotes [${learned.join(" ")}] (first build ${Date.now() - started} ms)\n`,
      )
      const path = join(targets, id, "Dockerfile")
      writeFileSync(path, withExpectedPromoted(readFileSync(path, "utf8"), learned))
      ensured = await ensure()
    }
    process.stderr.write(
      `lane: the generated ${id} image ${ensured.image.localId} (${ensured.build ? `built in ${ensured.build.ms} ms` : "recorded"}, ${Date.now() - started} ms in all)\n`,
    )
    return { ensured, learned }
  } finally {
    rmSync(targets, { recursive: true, force: true })
  }
}

/**
 * What the build log says of the promotion step: the set it printed (`#<step> <seconds>
 * b4-factory promoted: …`, never the echoed RUN line, which holds `$actual`), or `cached` when
 * BuildKit reused the layer from an earlier build of the same recipe on this host, which prints
 * no output at all (a second local run of the lanes; a fresh CI runner always runs the step).
 */
function promotionStepOutcome(log: string): "absent" | "cached" | string[] {
  const step = /^#(\d+) \[[^\]]*\] RUN .*EXPECTED_PROMOTED=/m.exec(log)?.[1]
  if (step === undefined) return "absent"
  if (new RegExp(`^#${step} CACHED$`, "m").test(log)) return "cached"
  const printed = new RegExp(`^#${step} \\S+ b4-factory promoted:([^\\n$"]*)$`, "m").exec(log)
  if (printed === null) return "absent"
  return (printed[1] as string).split(/\s+/).filter((name) => name.length > 0)
}

describe("a devkit target generated by target:init", () => {
  it("builds through the registry", async () => {
    const { ensured, learned } = await buildGenerated("@b4run/devkit", "devkit")
    // Nothing nests at the devkit pin: the empty set init writes is the right one.
    expect(learned).toBeUndefined()
    expect(ensured.image.localId).toMatch(/^sha256:[0-9a-f]{64}$/)
    expect(ensured.image.baseManifestDigest).toBe(
      "sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6",
    )
    // The build ran the promotion step (promoting nothing), or reused its layer; and every
    // module assertion passed in the image.
    if (ensured.build !== undefined)
      expect([[], "cached"]).toContainEqual(promotionStepOutcome(ensured.build.log))
  }, 5_000_000)
})

/**
 * The template's nested-typescript shim and its relinks by package name are exercised only by
 * cli (plan I9). Opt-in like the cli target's own lane (a 2 GB image): `test:sandbox:cli`
 * sets the variable, and PR 1 runs it once by hand before it merges.
 */
describe.skipIf(process.env.FACTORY_TEST_CLI_TARGET !== "1")(
  "a cli target generated by target:init",
  () => {
    it("learns the hand-written Dockerfile's promotion set from its first build, then builds", async () => {
      const { ensured, learned } = await buildGenerated("@b4run/cli", "cli")
      expect(learned).toEqual(
        expectedPromotedOf(readFileSync(join(targetsDir, "cli", "Dockerfile"), "utf8")),
      )
      expect(ensured.image.localId).toMatch(/^sha256:[0-9a-f]{64}$/)
    }, 5_000_000)
  },
)
