import { expect, it } from "vitest"
import * as view from "../../src/view/index.ts"

it("exports the framework-free view surface", () => {
  expect(Object.keys(view).sort()).toEqual([
    "B4_STEP_EVENT_NAME",
    "B4_STEP_STATUSES",
    "BUILT_IN_GROUP_LABELS",
    "CHECKLIST_TICK",
    "CHEVRON_GLYPH",
    "ELAPSED_TICK_MS",
    "EMPTY_TURNS",
    "MAX_APPROVAL_ARG_CHARS",
    "MAX_DETAIL_CHARS",
    "MAX_FIELD_CHARS",
    "NO_FLASH_MS",
    "STEP_GLYPHS",
    "approvalArgsRows",
    "approvalErrorLine",
    "approvalFromInterrupt",
    "approvalLabel",
    "approvalPayload",
    "approvalPrompt",
    "blocksToParts",
    "capDetail",
    "checklistBox",
    "countSources",
    "countSteps",
    "dispatchDecision",
    "eventsFromState",
    "formatDuration",
    "groupMeta",
    "groupSteps",
    "initialDisclosure",
    "isDisclosureOpen",
    "isSafeHref",
    "isSubagentLive",
    "isSubagentMessage",
    "nestedSummaryLine",
    "noFlashRemaining",
    "observeDisclosure",
    "ownEntry",
    "pendingApprovals",
    "phraseGroupLabel",
    "planProgress",
    "prettyValue",
    "readStepEvent",
    "reasoningLabel",
    "reduceTurns",
    "sampleElapsed",
    "scopeLine",
    "stepDetailText",
    "stepDetailView",
    "stepGlyph",
    "stepLabel",
    "stepMeta",
    "subagentMeta",
    "subagentRowState",
    "subagentSettledText",
    "summaryLine",
    "todoStatusLabel",
    "toggleDisclosure",
    "turnForMessage",
    "turnForToolCalls",
    "turnsFromState",
  ])
})

it("imports nothing from React", async () => {
  const source = await import("node:fs/promises").then((fs) =>
    Promise.all(
      [
        "index.ts",
        "activity-approval.ts",
        "activity-disclosure.ts",
        "activity-format.ts",
        "activity-glyphs.ts",
        "activity-lookup.ts",
        "activity-timing.ts",
        "labels.ts",
        "parts.ts",
        "messages.ts",
        "plan.ts",
        "step.ts",
        "turns.ts",
        "turns-from-state.ts",
      ].map((file) => fs.readFile(new URL(`../../src/view/${file}`, import.meta.url), "utf8")),
    ),
  )
  for (const text of source) expect(text).not.toMatch(/from "react"|@copilotkit/)
})
